---
- name: Install Packetbeat.
  package:
    name: "{{ packetbeat_package }}"
    state: "{{ packetbeat_package_state }}"

- name: Copy packetbeat configuration.
  template:
    src: "{{ packetbeat_template }}"
    dest: "/etc/{{ packetbeat_package }}/packetbeat.yml"
    owner: ubuntu
    group: ubuntu
    mode: 0644
  when: packetbeat_create_config | bool
  notify: restart packetbeat


  